### ISSUE TITLE
`codef` folders only

### ISSUE THREAD

**Issue by bowencool** [alexchantastic/alfred-open-with-vscode-workflow#6]
there ara too many files

**Comment by alexchantastic** [comment]
I don't think I'm going to make this change, but you are free to modify your copy to filter on folders.

You can do this by opening the workflow and editing the `codef` file filter node. You can then drag a folder (can be any folder) from Finder into the file types filter list.

The end result should look like this:

![image](https://user-images.githubusercontent.com/604167/150206843-e9441077-8600-4cf2-90ab-a75b9d0456dc.png)

**Comment by mijewe** [comment]
FYI my hack for this was to tag each of my project folders with the tag "project", and add a `kMDItemUserTags` = `project` to my Fields settings.

Not perfect because I have to remember to add the project tag, but it does mean that only top level project folders will show up in the filter, rather than all sub folders.
